name: Seguridad con Semgrep

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  semgrep:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Ejecutar Semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          config: "p/ci"         # Reglas predefinidas para CI
          generateSarif: true    # Para ver en Security tab

      - name: Subir reporte SARIF
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: semgrep.sarif
