name: Seguridad con Semgrep

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  semgrep:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Instalar Semgrep
        run: pip install semgrep

      - name: Ejecutar Semgrep con reglas de CI
        run: semgrep --config p/ci --sarif --output semgrep.sarif

      - name: Subir reporte SARIF
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: semgrep.sarif
